name: Bharat Jankari Live Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/bharatjankari.com/public_html

            git pull origin main

            npm install
            npm run build

            pm2 restart bharat-jankari || pm2 start npm --name "bharat-jankari" -- start